<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gerald Lim">
<meta name="dcterms.date" content="2024-02-25">

<title>IS415-GAA - Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3.2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_1.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_2.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5.2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 11</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03-NKDE.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3 NKDE</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex06.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex07.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex08.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex09/In-class_Ex09.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex10/In-class_Ex10.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#disclaimer-read-this-before-you-scroll-down" id="toc-disclaimer-read-this-before-you-scroll-down" class="nav-link active" data-scroll-target="#disclaimer-read-this-before-you-scroll-down"><strong>DISCLAIMER (Read this before you scroll down):</strong></a></li>
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene"><strong>Setting the Scene</strong></a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><strong>Objectives</strong></a></li>
  <li><a href="#install-maptools" id="toc-install-maptools" class="nav-link" data-scroll-target="#install-maptools">1 Install maptools</a></li>
  <li><a href="#data-import-wrangling-and-analysis" id="toc-data-import-wrangling-and-analysis" class="nav-link" data-scroll-target="#data-import-wrangling-and-analysis">2 Data Import, Wrangling and Analysis</a>
  <ul>
  <li><a href="#taiwan-village-data-taiwan_village_sf" id="toc-taiwan-village-data-taiwan_village_sf" class="nav-link" data-scroll-target="#taiwan-village-data-taiwan_village_sf">2.1 Taiwan Village Data (taiwan_village_sf)</a>
  <ul class="collapse">
  <li><a href="#import-the-csv-data-tainan_village.shp" id="toc-import-the-csv-data-tainan_village.shp" class="nav-link" data-scroll-target="#import-the-csv-data-tainan_village.shp">2.1.1 Import the csv data (TAINAN_VILLAGE.shp)</a></li>
  <li><a href="#filtering-the-taiwan_village_sf." id="toc-filtering-the-taiwan_village_sf." class="nav-link" data-scroll-target="#filtering-the-taiwan_village_sf.">2.1.2 Filtering the taiwan_village_sf.</a></li>
  <li><a href="#saving-it-to-rds" id="toc-saving-it-to-rds" class="nav-link" data-scroll-target="#saving-it-to-rds">2.1.3 Saving it to RDS</a></li>
  <li><a href="#visualise-the-dataset-by-plotting-it" id="toc-visualise-the-dataset-by-plotting-it" class="nav-link" data-scroll-target="#visualise-the-dataset-by-plotting-it">2.1.4 Visualise the dataset by plotting it</a></li>
  </ul></li>
  <li><a href="#dengue-data-dengue_sf" id="toc-dengue-data-dengue_sf" class="nav-link" data-scroll-target="#dengue-data-dengue_sf">2.2 Dengue Data (dengue_sf)</a>
  <ul class="collapse">
  <li><a href="#import-the-csv-data-dengue_daily.csv" id="toc-import-the-csv-data-dengue_daily.csv" class="nav-link" data-scroll-target="#import-the-csv-data-dengue_daily.csv">2.2.1 Import the csv data (Dengue_Daily.csv)</a></li>
  <li><a href="#filtering-the-dengue_sf" id="toc-filtering-the-dengue_sf" class="nav-link" data-scroll-target="#filtering-the-dengue_sf">2.2.2 Filtering the dengue_sf</a></li>
  <li><a href="#basic-analysis-of-filtered_dengue_sf-dataset" id="toc-basic-analysis-of-filtered_dengue_sf-dataset" class="nav-link" data-scroll-target="#basic-analysis-of-filtered_dengue_sf-dataset">2.2.3 Basic Analysis of filtered_dengue_sf dataset</a></li>
  <li><a href="#saving-it-to-rds-1" id="toc-saving-it-to-rds-1" class="nav-link" data-scroll-target="#saving-it-to-rds-1">2.2.4 Saving it to RDS</a></li>
  </ul></li>
  <li><a href="#performing-join-operation-to-combine-both-data-sets" id="toc-performing-join-operation-to-combine-both-data-sets" class="nav-link" data-scroll-target="#performing-join-operation-to-combine-both-data-sets">2.3 Performing Join operation to combine both data sets</a>
  <ul class="collapse">
  <li><a href="#left-join-operation-and-outcome" id="toc-left-join-operation-and-outcome" class="nav-link" data-scroll-target="#left-join-operation-and-outcome">2.3.1 Left-Join Operation and Outcome</a></li>
  <li><a href="#saving-it-to-rds-2" id="toc-saving-it-to-rds-2" class="nav-link" data-scroll-target="#saving-it-to-rds-2">2.3.2 Saving it to RDS</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#global-spatial-autocorrelation-analysis-by-using-sfdep-methods" id="toc-global-spatial-autocorrelation-analysis-by-using-sfdep-methods" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-analysis-by-using-sfdep-methods">3 Global spatial autocorrelation analysis by using sfdep methods</a>
  <ul>
  <li><a href="#visualizing-taiwan_village_dengue" id="toc-visualizing-taiwan_village_dengue" class="nav-link" data-scroll-target="#visualizing-taiwan_village_dengue">3.1 Visualizing taiwan_village_dengue</a></li>
  <li><a href="#global-measures-of-spatial-autocorrelation" id="toc-global-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-measures-of-spatial-autocorrelation">3.2 Global Measures of Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">3.2.1 Computing Contiguity Spatial Weights</a></li>
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix">3.2.2 Row-standardised weights matrix</a></li>
  </ul></li>
  <li><a href="#global-measures-of-spatial-autocorrelation-morans-i-and-gearys-c" id="toc-global-measures-of-spatial-autocorrelation-morans-i-and-gearys-c" class="nav-link" data-scroll-target="#global-measures-of-spatial-autocorrelation-morans-i-and-gearys-c">3.3 Global Measures of Spatial Autocorrelation: Moran’s I and Geary’s C</a>
  <ul class="collapse">
  <li><a href="#morans-i-test" id="toc-morans-i-test" class="nav-link" data-scroll-target="#morans-i-test">3.3.1 Moran’s I Test</a></li>
  <li><a href="#monte-carlo-morans-i" id="toc-monte-carlo-morans-i" class="nav-link" data-scroll-target="#monte-carlo-morans-i">3.3.2 Monte Carlo Moran’s I</a></li>
  <li><a href="#visualising-monte-carlo-morans-i" id="toc-visualising-monte-carlo-morans-i" class="nav-link" data-scroll-target="#visualising-monte-carlo-morans-i">3.3.3 Visualising Monte Carlo Moran’s I</a></li>
  <li><a href="#gearys-c-test" id="toc-gearys-c-test" class="nav-link" data-scroll-target="#gearys-c-test">3.3.4 Geary’s C Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#local-spatial-autocorrelation-analysis-by-using-sfdep-methods" id="toc-local-spatial-autocorrelation-analysis-by-using-sfdep-methods" class="nav-link" data-scroll-target="#local-spatial-autocorrelation-analysis-by-using-sfdep-methods">4 Local spatial autocorrelation analysis by using sfdep methods</a></li>
  <li><a href="#analyising-emerging-hotspot-analysis-by-using-sfdep-methods" id="toc-analyising-emerging-hotspot-analysis-by-using-sfdep-methods" class="nav-link" data-scroll-target="#analyising-emerging-hotspot-analysis-by-using-sfdep-methods">5 Analyising emerging hotspot analysis by using sfdep methods</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gerald Lim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="disclaimer-read-this-before-you-scroll-down" class="level2">
<h2 class="anchored" data-anchor-id="disclaimer-read-this-before-you-scroll-down"><strong>DISCLAIMER (Read this before you scroll down):</strong></h2>
<ol type="1">
<li><p><strong>Some parts of this document have hidden codes that are kept PRIVATE for now. They contain confidential codes which I will ONLY be disclosing them on 1 March 2024 (week 9).</strong></p></li>
<li><p><strong>I will ONLY provide explanations for the exercise right now, and it is subjected to change during the duration of this exercise.</strong></p></li>
<li><p><strong>It is important to be honest and fair in our work, and respect the privacy of the work of others, so as to uphold academic integrity throughout the duration of this take-home exercise.</strong></p></li>
</ol>
</section>
<section id="setting-the-scene" class="level2">
<h2 class="anchored" data-anchor-id="setting-the-scene"><strong>Setting the Scene</strong></h2>
<p>Dengue Hemorrhagic Fever (in short dengue fever) is one of the most widespread mosquito-borne diseases in the most tropical and subtropical regions. It is an acute disease caused by dengue virus infection which is transmitted by female Aedes aegypti and Aedes albopictus mosquitoes. In 2015, Taiwan had recorded the most severe dengue fever outbreak with more than 43,000 dengue cases and 228 deaths. Since then, the annual reported dengue fever cases were maintained at the level of not more than 200 cases. However, in 2023, Taiwan recorded 26703 dengue fever cases. Figure below reveals that more than 25,000 cases were reported at Tainan City.</p>
<p><img src="https://is415-ay2023-24t2.netlify.app/img/df1.jpg" class="img-fluid"></p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives"><strong>Objectives</strong></h2>
<p>As a curious geospatial analytics green horn, you are interested to discover:</p>
<ul>
<li><p>if the distribution of dengue fever outbreak at Tainan City, Taiwan are independent from space and space and time.</p></li>
<li><p>If the outbreak is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.</p></li>
</ul>
</section>
<section id="install-maptools" class="level2">
<h2 class="anchored" data-anchor-id="install-maptools">1 Install maptools</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"maptools"</span>, <span class="at">repos =</span> <span class="st">"https://packagemanager.posit.co/cran/2023-10-13"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Installing the required tools for the analysis (e.g.&nbsp;sf, tidyverse, maptools, etc)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(maptools, sf, raster, spatstat, tmap, tidyverse, arrow, lubridate, dplyr, spNetwork, spacetime, spdep, sfdep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-import-wrangling-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-import-wrangling-and-analysis">2 Data Import, Wrangling and Analysis</h2>
<p>This is where we import the data and prepare it before analysis.</p>
<p>Let’s use st_read() of sf package to import these two geospatial data sets into R. And we will be using other functions to prepare our data upon importing them. Moreover, we will also perform some simple operation on the datasets to gather some basic analysis.</p>
<p>The 2 data sets are:</p>
<ul>
<li><p>TAIWAN_VILLAGE_2020, a geospatial data of village boundary of Taiwan. It is in ESRI shapefile format. The data is in Taiwan Geographic Coordinate System. (Source: <a href="https://data.gov.tw/en/datasets/130549">Historical map data of the village boundary: TWD97 longitude and latitude</a>)</p></li>
<li><p>Dengue_Daily.csv, an aspatial data of reported dengue cases in Taiwan since 1998. (Source: <a href="https://data.cdc.gov.tw/en/dataset/dengue-daily-determined-cases-1998">Dengue Daily Confirmed Cases Since 1998</a>. Below are selected fields that are useful for this study:</p>
<ul>
<li><p>發病日: Onset date</p></li>
<li><p>最小統計區中心點X: x-coordinate</p></li>
<li><p>最小統計區中心點Y: y-coordinate</p></li>
</ul></li>
</ul>
<section id="taiwan-village-data-taiwan_village_sf" class="level3">
<h3 class="anchored" data-anchor-id="taiwan-village-data-taiwan_village_sf">2.1 Taiwan Village Data (taiwan_village_sf)</h3>
<section id="import-the-csv-data-tainan_village.shp" class="level4">
<h4 class="anchored" data-anchor-id="import-the-csv-data-tainan_village.shp">2.1.1 Import the csv data (TAINAN_VILLAGE.shp)</h4>
<p>Firstly, we will import the data for the Taiwan Village Data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>taiwan_village_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"TAINAN_VILLAGE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s check the referencing system info of this taiwan_village_sf</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(taiwan_village_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="filtering-the-taiwan_village_sf." class="level4">
<h4 class="anchored" data-anchor-id="filtering-the-taiwan_village_sf.">2.1.2 Filtering the taiwan_village_sf.</h4>
<p>Currently, we have 649 rows of data in taiwan_village_sf.</p>
<p><img src="images/clipboard-933829746.png" class="img-fluid"></p>
<p>Therefore, we have to filter the taiwan_village_sf for village level of D01, D02, D04, D06, D07, D08, D32, and D39 of the Tainan City, Taiwan</p>
<p>Now, filtered_taiwan_village_sf will consist of 258 rows of data. This will help to reduce the amount of data that is needed to be processed in the later parts.</p>
<p><img src="images/clipboard-1325127262.png" class="img-fluid"></p>
</section>
<section id="saving-it-to-rds" class="level4">
<h4 class="anchored" data-anchor-id="saving-it-to-rds">2.1.3 Saving it to RDS</h4>
<p>Since we’re happy with the dataset for filtered_taiwan_village_sf, let’s save it to a rds so that it would be easier for us to retrieve it in the future</p>
<p>Import the filtered_taiwan_village_sf rds data</p>
</section>
<section id="visualise-the-dataset-by-plotting-it" class="level4">
<h4 class="anchored" data-anchor-id="visualise-the-dataset-by-plotting-it">2.1.4 Visualise the dataset by plotting it</h4>
<p>Let’s visualise how filtered_taiwan_village_sf looks like when we plot it</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="dengue-data-dengue_sf" class="level3">
<h3 class="anchored" data-anchor-id="dengue-data-dengue_sf">2.2 Dengue Data (dengue_sf)</h3>
<section id="import-the-csv-data-dengue_daily.csv" class="level4">
<h4 class="anchored" data-anchor-id="import-the-csv-data-dengue_daily.csv">2.2.1 Import the csv data (Dengue_Daily.csv)</h4>
<p>Firstly, we will import the data for the Dengue Data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dengue_sf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/Dengue_Daily.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As dengue_sf consists of 106861 rows of data, with 26 types of variables, as shown below. Therefore we need to filter it</p>
<p><img src="images/clipboard-342559558.png" class="img-fluid"></p>
</section>
<section id="filtering-the-dengue_sf" class="level4">
<h4 class="anchored" data-anchor-id="filtering-the-dengue_sf">2.2.2 Filtering the dengue_sf</h4>
<p>Let’s filter dengue_sf for fever cases that are confined to epidemiology week 31-50 of 2023, as well as the selected variables which we will be working with (發病日: Onset date, 居住縣市: County, 居住鄉鎮: Town, 居住村里: Village, 最小統計區中心點X: x-coordinate, 最小統計區中心點Y: y-coordinate)</p>
<p>In the code chunk above, we filtered the specific data that falls under the weeks that we are interested to look into. Moreover, we also use the “select” line to select the specific variables that we deemed useful for our research.</p>
<p>After filtering dengue_sf, and storing it in filtered_dengue_sf, the amount of data has reduced significantly from 106861 rows of data in dengue_sf, to 25480 rows of data in filtered_dengue_sf (with 3 types of variables).</p>
<p><img src="images/clipboard-1392265263.png" class="img-fluid"></p>
<p>Let’s check the data type of each variable before we proceed to performing left-join</p>
<p>Let’s transform some of our variables and prepare it for the left-join operation in step 2.3</p>
<ul>
<li>Since the X and Y coordinates are in string format, we need to convert it to numeric.</li>
<li>This is the same for onset date where we need to convert it to date format</li>
</ul>
<p>Let’s create 3 different variables that stores the week number, month and day respectively. This is to facilitate our research and analysis in the later parts of this take-home exercise.</p>
<p>However, in our dengue dataset, we have noticed that there are rows of data with no village name. As our research is focused mainly on the village level, we will remove the rows with village name = “None”. [SKIP FIRST]</p>
<p><img src="images/clipboard-459349656.png" class="img-fluid" width="612"></p>
</section>
<section id="basic-analysis-of-filtered_dengue_sf-dataset" class="level4">
<h4 class="anchored" data-anchor-id="basic-analysis-of-filtered_dengue_sf-dataset">2.2.3 Basic Analysis of filtered_dengue_sf dataset</h4>
<p>Since we have the finalised filtered_dengue_sf, it is important for us to create a new table to store the number of cases, grouped by the <strong>day</strong> and <strong>village</strong>. We will store it in cases_by_day_village dataset.</p>
<p>A snippet of the resulting dataset for <strong>cases_by_day_village</strong> looks like this:</p>
<p><img src="images/clipboard-3333388626.png" class="img-fluid" width="450"></p>
<p>In addition to the cases_by_day_village dataset, it would be useful for us to create a new table to store the number of cases, grouped by the <strong>week</strong> and <strong>village</strong>. We will store it in <strong>cases_by_week_village</strong> dataset.</p>
<p>A snippet of the resulting dataset for <strong>cases_by_week_village</strong> looks like this:</p>
<p><img src="images/clipboard-2633481134.png" class="img-fluid" width="537"></p>
<p>To get the number of cases in througout Tainan city during the whole epidemiology week 31-50, it would be useful for us to create a new table to store the number of cases for each village. We will store it in <strong>cases_by_village</strong> dataset.</p>
<p>A snippet of the resulting dataset for <strong>cases_by_village</strong> looks like this:</p>
<p><img src="images/clipboard-483203027.png" class="img-fluid" width="433"></p>
<p>To get the number of cases in a week througout Tainan city, it would be useful for us to create a new table to store the number of cases, grouped by the <strong>week</strong> alone. We will store it in <strong>cases_by_week</strong> dataset.</p>
<p>A snippet of the resulting dataset for <strong>cases_by_week</strong> looks like this:</p>
<p><img src="images/clipboard-941645063.png" class="img-fluid"></p>
<p>Now, we have found valuable analysis from our dataset, let’s move on to the next section where we keep them in rds form.</p>
</section>
<section id="saving-it-to-rds-1" class="level4">
<h4 class="anchored" data-anchor-id="saving-it-to-rds-1">2.2.4 Saving it to RDS</h4>
<p>Since we’re happy with the dataset for filtered_taiwan_village_sf, and datasets from our analysis in 2.2.3, let’s save it to a rds so that it would be easier for us to retrieve it in the future</p>
<p>Import the filtered_taiwan_village_sf rds data</p>
<p>Let’s take a look at our Dengue datasets in 2.2 before we move on to 2.3 :)</p>
<p><strong>filtered_dengue_sf</strong></p>
<ul>
<li>I have included the 居住縣市 (County), 居住鄉鎮 (Town) and 居住村里 (Village) into the data set for easier future reference.</li>
</ul>
<p><img src="images/clipboard-2567583851.png" class="img-fluid" width="829"></p>
</section>
</section>
<section id="performing-join-operation-to-combine-both-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="performing-join-operation-to-combine-both-data-sets">2.3 Performing Join operation to combine both data sets</h3>
<p>Let’s perform a join operation to combine the variables in filtered_taiwan_village_sf and filtered_dengue_sf.</p>
<p>Our goal is to perform the join operation to the <strong>cases_by_week_village</strong> and supplement it with the specific geospatial and relevant variable. We will be operating the join operation based on the Village Name of both dataset as we want to retrieve the distinct geospatial infromation from <strong>filtered_taiwan_village_sf</strong> for each dengue cases.</p>
<p>The reason for using cases_by_week_village is because we are focusing on the number of cases in each village on a weekly basis.</p>
<section id="left-join-operation-and-outcome" class="level4">
<h4 class="anchored" data-anchor-id="left-join-operation-and-outcome">2.3.1 Left-Join Operation and Outcome</h4>
<p>Before we perform the left-join operation, we can see that the cases_by_village is not a spatial data. As for filtered_taiwan_village_sf, we have already checked the data type of the file is already in spatial data type (TWD97).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(cases_by_week_village)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System: NA</code></pre>
</div>
</div>
<p>Therefore we have to convert the cases_by_village dataset into a spatial data.</p>
<p>Before we transform it into a spatial data, we have to vet through our data in cases_by_village and case_by_village dataset. There are rows where there are “NA” values for the village name, X and Y coordinates, which could potentially cause issues in the future analysis.</p>
<p><img src="images/clipboard-977836271.png" class="img-fluid"></p>
<p>And we have to clean up the NA values before proceeding to case_by_village into a spatial data.</p>
<p>One option that we could remove the NA values which could potentially create problems in our future analysis, and they wouldn’t provide us with accurate analysis. On the other hand, if we were to adopt the other option which is to find the mean / median of the x and y coordinates for the missing values, it would also affect the accuracy of our analysis.</p>
<p>Now that we have cleared the NA values, let’s transform the case_by_village dataset into a sf</p>
<p>The join dataset would be named taiwan_village_dengue</p>
<p>After performing the left-join operation, the taiwan_village_dengue dataset seems to have “NA” values. This is due to the fact that the village name (居住村里) value in the filtered_dengue_sf is not found in the list of village name (VILLNAME) in filtered_taiwan_village_sf.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: TWD97 
  wkt:
GEOGCRS["TWD97",
    DATUM["Taiwan Datum 1997",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands."],
        BBOX[17.36,114.32,26.96,123.61]],
    ID["EPSG",3824]]</code></pre>
</div>
</div>
</section>
<section id="saving-it-to-rds-2" class="level4">
<h4 class="anchored" data-anchor-id="saving-it-to-rds-2">2.3.2 Saving it to RDS</h4>
<p>Since we are happy with our finalised taiwan_village_dengue dataset, let’s keep it in our rds for easy reference in the future</p>
<p>Import the filtered_taiwan_village_sf rds data</p>
<p>Let’s take a look at our taiwan_village_dengue dataset :)</p>
<p><img src="images/clipboard-585552616.png" class="img-fluid"></p>
<p>Let’s plot <strong>taiwan_village_dengue</strong> and see how it looks like.</p>
<p>We will create an “<strong>agg_data</strong>” dataset to count the number of cases in each village, and thereafter plot it on tmap, so that we can easily identify which village has a higher number of cases on the map.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the map, we can see that there are some villages that have a significantly higher number of cases. If we look at our <strong>agg_data</strong> dataset, we can see that these are the villages with the highest number of cases.</p>
<p><img src="images/clipboard-2228245534.png" class="img-fluid" width="428"></p>
</section>
</section>
</section>
<section id="global-spatial-autocorrelation-analysis-by-using-sfdep-methods" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation-analysis-by-using-sfdep-methods">3 Global spatial autocorrelation analysis by using sfdep methods</h2>
<section id="visualizing-taiwan_village_dengue" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-taiwan_village_dengue">3.1 Visualizing taiwan_village_dengue</h3>
<p>Let’s visualize taiwan_village_dengue before we move on to performing global spatial autocorrelation analysis</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="global-measures-of-spatial-autocorrelation" class="level3">
<h3 class="anchored" data-anchor-id="global-measures-of-spatial-autocorrelation">3.2 Global Measures of Spatial Autocorrelation</h3>
<p>We will be performing Global Measures of Spatial Autocorrelation in this section.</p>
<section id="computing-contiguity-spatial-weights" class="level4">
<h4 class="anchored" data-anchor-id="computing-contiguity-spatial-weights">3.2.1 Computing Contiguity Spatial Weights</h4>
<p>Before we can perform the global spatial autocorrelation analysis, we need to construct the spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units.</p>
<p>The code calculates a spatial weights matrix using the queen contiguity criterion for the villages in Taiwan represented by polygons in the taiwan_village_dengue dataset, and then provides a summary of this matrix.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 13712 
Number of nonzero links: 6686482 
Percentage nonzero weights: 3.556281 
Average number of links: 487.6373 
Link number distribution:

  16   17   19   20   25   26   27   32   38   45   51   55   57   62   64   69 
   4    2    2    1   10    2   10    1    3    3   11   32   18   12   31   25 
  71   80   82   83   91   93   98  100  105  106  110  111  112  113  115  119 
   9   16   12   13   29   12    4    9   15   16    3   22    8   30   17   28 
 122  124  127  128  131  137  139  143  149  156  163  164  167  172  180  183 
  17   45   23   32   15    7   36   24   12   28   20   20   55   25   14   25 
 184  188  189  193  198  200  204  212  218  224  226  227  228  229  236  237 
  14   18   30   16   61   52   10   21   60   25   16   31   32   60   68   29 
 246  249  250  252  254  257  263  273  274  284  285  286  290  296  297  299 
 119   17   54   26  115   60   48   84   61   45   67   29   28   46  104   15 
 301  307  310  312  314  318  322  323  328  329  336  342  343  348  350  352 
  58   35   60   67   67  210   92   24  105  108   46   79   20   10  179   68 
 357  358  365  372  375  384  385  386  388  390  394  397  399  401  402  404 
  38  137   98   56   38  121   48   63   74  139  103   51   18   63   35  131 
 407  412  413  416  419  420  426  431  432  433  434  435  436  443  445  446 
 143   65  110  116  124  141   65   72   74   31   34   73   32  187   72   69 
 453  454  457  459  462  465  467  468  470  473  477  481  487  495  497  501 
  55   78  134   67   47   86  170   41   99   67   45   61   45  119   91   53 
 502  503  507  508  509  511  512  515  526  527  528  529  530  536  538  541 
  99  126   50   66  133   55  117  102   11   83   54  108  125  122  191  202 
 542  550  554  558  561  568  571  576  577  585  591  593  594  595  596  603 
  43   47   91   47   77   96   48   69   92   38   55   57   42  114  112   80 
 608  610  616  622  623  631  636  639  640  652  655  657  658  664  673  679 
  20  113  123  245  138   97  133   68   72  105  105   53   74  130   58  144 
 702  707  714  729  731  732  752  768  773  779  794  799  840  868  877  879 
  67   66   91   70   80   49   92   43   86   71   74   97   60  107  111   84 
 894  899  905  919 1056 
 179  102  117  131  129 
4 least connected regions:
160 160.1 160.2 160.3 with 16 links
129 most connected regions:
36 36.1 36.2 36.3 36.4 36.5 36.6 36.7 36.8 36.9 36.10 36.11 36.12 36.13 36.14 36.15 36.16 36.17 36.18 36.19 36.20 36.21 36.22 36.23 36.24 36.25 36.26 36.27 36.28 36.29 36.30 36.31 36.32 36.33 36.34 36.35 36.36 36.37 36.38 36.39 36.40 36.41 36.42 36.43 36.44 36.45 36.46 36.47 36.48 36.49 36.50 36.51 36.52 36.53 36.54 36.55 36.56 36.57 36.58 36.59 36.60 36.61 36.62 36.63 36.64 36.65 36.66 36.67 36.68 36.69 36.70 36.71 36.72 36.73 36.74 36.75 36.76 36.77 36.78 36.79 36.80 36.81 36.82 36.83 36.84 36.85 36.86 36.87 36.88 36.89 36.90 36.91 36.92 36.93 36.94 36.95 36.96 36.97 36.98 36.99 36.100 36.101 36.102 36.103 36.104 36.105 36.106 36.107 36.108 36.109 36.110 36.111 36.112 36.113 36.114 36.115 36.116 36.117 36.118 36.119 36.120 36.121 36.122 36.123 36.124 36.125 36.126 36.127 36.128 with 1056 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 13711area units in Tainan City. The observations are:</p>
<ul>
<li><p>There are 129 <strong>most connected area unit</strong> which has 1056 neighbors</p></li>
<li><p>There are 4 <strong>least connected area units</strong> with only 15 neighbors</p></li>
</ul>
</section>
<section id="row-standardised-weights-matrix" class="level4">
<h4 class="anchored" data-anchor-id="row-standardised-weights-matrix">3.2.2 Row-standardised weights matrix</h4>
<p>Let’s assign weights to each neighboring polygon before we move on to performing our Maron’s I test.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 13712 
Number of nonzero links: 6686482 
Percentage nonzero weights: 3.556281 
Average number of links: 487.6373 

Weights style: W 
Weights constants summary:
      n        nn    S0       S1       S2
W 13712 188018944 13712 71.85066 55847.45</code></pre>
</div>
</div>
</section>
</section>
<section id="global-measures-of-spatial-autocorrelation-morans-i-and-gearys-c" class="level3">
<h3 class="anchored" data-anchor-id="global-measures-of-spatial-autocorrelation-morans-i-and-gearys-c">3.3 Global Measures of Spatial Autocorrelation: Moran’s I and Geary’s C</h3>
<section id="morans-i-test" class="level4">
<h4 class="anchored" data-anchor-id="morans-i-test">3.3.1 Moran’s I Test</h4>
<p>We will be using Moran’s I statistics to test our taiwan_village_dengue dataset.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  taiwan_village_dengue$Num_Cases  
weights: rswm_q 
omitted: 9195   

Moran I statistic standard deviate = 47.203, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     2.866868e-02     -7.293946e-05      3.707573e-07 </code></pre>
</div>
</div>
<p>Based on the output, the Moran I statistic standard deviate measures the degree of spatial autocorrelation in the variable, Num_cases, in the taiwan_viilage_dengue dataset. In this case, it is 47.203, which indicates a high level of spatial autocorrelation.</p>
<p>In addition, the p-value is low, at less than 2.2e-16, which indicates that the the spatial correlation is statistically significant. This rejects the null hypothesis that there is no spatial autocorrelation in the data.</p>
<p>Based on the above explanation, it suggests that the areas with high number of dengue cases tend to be clustered together geographically.</p>
</section>
<section id="monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-morans-i">3.3.2 Monte Carlo Moran’s I</h4>
<p>Let’s perform simulation on our Moran’s I test</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>bperm<span class="ot">=</span> <span class="fu">moran.mc</span>(taiwan_village_dengue<span class="sc">$</span>Num_Cases, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">listw=</span>rswm_q, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action=</span>na.omit)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>bperm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  taiwan_village_dengue$Num_Cases 
weights: rswm_q 
omitted: 9195 
number of simulations + 1: 1000 

statistic = 0.028669, observed rank = 1000, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>The result indicates that the spatial autocorrelation is statistically significant with the p-value of 0.001.</p>
</section>
<section id="visualising-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualising-monte-carlo-morans-i">3.3.3 Visualising Monte Carlo Moran’s I</h4>
<p>Let’s display our findings in a histogram so that we can visualise it better</p>
<p>Firstly, we can get a statistical summary of the Monte Carlo Moran’s I output</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-1.716e-03 -5.032e-04 -9.828e-05 -5.830e-05  3.200e-04  2.120e-03 </code></pre>
</div>
</div>
<p>Now, we can plot the histogram</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bperm<span class="sc">$</span>res, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq=</span><span class="cn">TRUE</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">150</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Simulated Moran's I"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.002</span>, <span class="fl">0.002</span>))</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="gearys-c-test" class="level4">
<h4 class="anchored" data-anchor-id="gearys-c-test">3.3.4 Geary’s C Test</h4>
<p>Since we have performed the Moran’s I test before this step, we have seen the spatial clustering and dispersion in our dataset, particularly the number of dengue cases in each village.</p>
<p>Now, we will perform Geary’s C test to dive into the differences in attribute values between the neighboring observations.</p>
</section>
</section>
</section>
<section id="local-spatial-autocorrelation-analysis-by-using-sfdep-methods" class="level2">
<h2 class="anchored" data-anchor-id="local-spatial-autocorrelation-analysis-by-using-sfdep-methods">4 Local spatial autocorrelation analysis by using sfdep methods</h2>
</section>
<section id="analyising-emerging-hotspot-analysis-by-using-sfdep-methods" class="level2">
<h2 class="anchored" data-anchor-id="analyising-emerging-hotspot-analysis-by-using-sfdep-methods">5 Analyising emerging hotspot analysis by using sfdep methods</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>